config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :molecules
  resources :sketchtrainings
  resources :techniques

  root 'molecules#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/molecule.rb
class Molecule < ApplicationRecord
  def next_molecule
      all_molecules = Molecule.all
      current_molecule_index = all_molecules.index(self)
      all_molecules[current_molecule_index + 1]
  end

  def first_molecule
    all_molecules = Molecule.all
    all_molecules[0]
  end
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/sketchtraining.rb
class Sketchtraining < ApplicationRecord
end

app/models/technique.rb
class Technique < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/molecules_controller.rb
class MoleculesController < ApplicationController

	before_action :find_molecule, only: [:show]
	before_action :train_sketch, only: [:show, :new]

	def index
  		@molecules = Molecule.all
			if((params["s_id"]).nil? == false)
				@sessionID = (params["s_id"])
				$version = (params["version"])

				puts "session saved"
				session[:current_sID] = @sessionID
				session[:current_version] = @version
			elsif(session[:current_sID].nil? == false)
				@sessionID = session[:current_sID]
				$version = session[:current_version]
			else
				@sessionID = ""
				$version = ""
			end

			puts @sessionID
			puts $version
  end

  def show
		@numAtoms = @molecule.num_atoms
		@cenAtom = @molecule.central_atom.to_s
		@othAtoms = @molecule.other_atoms.to_s
		@fullElectrons = @molecule.fullElectrons.to_s
		@availElectrons = @molecule.availElectrons.to_s
		@charge = @molecule.charge.to_s
		@formalCharges = @molecule.formalCharges.to_s
  end

	def create

	  puts "create hit!"

		newSketch = [ActiveSupport::JSON.decode(params["cosineStartAngle"]), ActiveSupport::JSON.decode(params["sineStartAngle"]), ActiveSupport::JSON.decode(params["BBDiagLen"]), ActiveSupport::JSON.decode(params["BBDiagAngle"]), ActiveSupport::JSON.decode(params["startEndDist"]), ActiveSupport::JSON.decode(params["startEndCosineAngle"]), ActiveSupport::JSON.decode(params["startEndSineAngle"]), ActiveSupport::JSON.decode(params["strokeLength"]), ActiveSupport::JSON.decode(params["angleTrav9"]), ActiveSupport::JSON.decode(params["angleTrav10"]), ActiveSupport::JSON.decode(params["angleTrav11"]), ActiveSupport::JSON.decode(params["maxSpeed"]), ActiveSupport::JSON.decode(params["pathDuration"])]

		decision = $dec_tree.predict(newSketch)

		@result = {interp: decision}
		render json: @result

	end

	def update
		puts "update molecule"

	end

	def new

	end

  def find_molecule
  		@molecule = Molecule.find(params[:id])
 	end

	def train_sketch
		@trainings = Sketchtraining.all

		training = []
		for t in @trainings
			newTraining = [t.cosineStartAngle, t.sineStartAngle, t.bbDiagLen, t.bbDiagAngle, t.startEndDist, t.startEndCosineAngle, t.startEndSineAngle, t.strokeLength, t.angleTrav9, t.angleTrav10, t.angleTrav11, t.maxSpeed, t.pathDuration, t.interpretation]
		  training.push(newTraining)
		end

		#train decision tree
		attributes = ['cosineStartAngle', 'sineStartAngle', 'bbDiagLen', 'bbDiagAngle', 'startEndDist', 'startEndCosineAngle', 'startEndSineAngle', 'strokeLength', 'angleTrav9', 'angleTrav10', 'angleTrav11', 'maxSpeed', 'pathDuration']

		$dec_tree = DecisionTree::ID3Tree.new(attributes, training, 'bond', :continuous)
		trainResult = $dec_tree.train
		puts "training complete"
	end

	private
    def sketchtraining_params
      params.require(:sketchtraining).permit(:interpretation)
    end





end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
  	@posts = Post.all.order("created_at DESC")
  end
  
  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)

  	if @post.save
  		redirect_to @post
  	else
  		render 'new'
  	end
  end

  def show
  	
  end

  def edit
  	
  end

  def update
  	if @post.update(post_params)
  		redirect_to @post
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@post.destroy
  	redirect_to root_path
  end

  private

  def find_post
  	@post = Post.find(params[:id])
  end

  def post_params
  	params.require(:post).permit(:title, :body)
  end


end

app/controllers/sketchtrainings_controller.rb
class SketchtrainingsController < ApplicationController


		def index
  		@sketchtrainings = Sketchtraining.all
			@molecules = Molecule.all
			@molecule = @molecules[0]
  	end

  	def new
			@sketchtrainings = Sketchtraining.all
			@sketchtraining = Sketchtraining.new
  	end

		def show
			@sketchtrainings = Sketchtraining.all
		end

  	def create
			puts "sketchtraining create hit"
  		t = Sketchtraining.new
			t.cosineStartAngle = ActiveSupport::JSON.decode(params["cosineStartAngle"])
			t.sineStartAngle = ActiveSupport::JSON.decode(params["sineStartAngle"])
			t.bbDiagLen = ActiveSupport::JSON.decode(params["BBDiagLen"])
			t.bbDiagAngle = ActiveSupport::JSON.decode(params["BBDiagAngle"])
			t.startEndDist = ActiveSupport::JSON.decode(params["startEndDist"])
			t.startEndCosineAngle = ActiveSupport::JSON.decode(params["startEndCosineAngle"])
			t. startEndSineAngle = ActiveSupport::JSON.decode(params["startEndSineAngle"])
			t. strokeLength = ActiveSupport::JSON.decode(params["strokeLength"])
			t.angleTrav9 = ActiveSupport::JSON.decode(params["angleTrav9"])
			t.angleTrav10 = ActiveSupport::JSON.decode(params["angleTrav10"])
			t.angleTrav11 = ActiveSupport::JSON.decode(params["angleTrav11"])
			t.maxSpeed = ActiveSupport::JSON.decode(params["maxSpeed"])
			t.pathDuration = ActiveSupport::JSON.decode(params["pathDuration"])
			t.interpretation = params["interpretation"]
			t.save

			@result = t.cosineStartAngle
			puts "#{t.interpretation} saved"
			render json: @result

		end

		def sketchtraining_params
  		params.require(:sketchtraining).permit(:interpretation)
  	end


end

app/controllers/techniques_controller.rb
class TechniquesController < ApplicationController
  def index
    @techniques = Technique.all
  end

  def new
    @techniques = Technique.all
    @techniques = Technique.new
  end

  def create
    puts "technique create hit"
    t = Technique.new
    t.session = params["id"]
    t.molecule = params["molecule"]
    t.techType = params["type"]
    t.time = params["time"]

    t.save

    @result = t.techType
    puts "#{t.techType} saved"
    render json: @result
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/molecules_helper.rb
module MoleculesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sketchtrainings_helper.rb
module SketchtrainingsHelper
end

app/helpers/techniques_helper.rb
module TechniquesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="apple-mobile-web-app-title" content="chemisketch">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <link rel="apple-touch-icon" href="/images/apple-touch-icon.png">
    <link rel="apple-touch-startup-image" href="/images/apple-touch-icon.png">
    <meta http-equiv="Page-Enter" content="blendTrans(Duration=.01)" />
    <meta http-equiv="Page-Exit" content="blendTrans(Duration=.01)" />
    <title>chemisketch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.12.0"> </script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/molecules/index.html.erb
<% counter = 0 %>
<div class="mainHeader headerwhite row">
        <div class="col-md-3 buttonSection">
            <button class="menuButton" id="myBtn">SESSION</button>
        </div>
        <div class="col-md-5">
          <h2>chemisketch</h2>
        </div>
</div>

<div class ="moleculeSelectorSection">
  <div id="myModal" class="modal">
    <div class="modal-content">
      <span class="close">&times;</span>
      <p id="currentSession"></p>
      <p id="errorSession"></p>
      <form>
        Change Session ID: <input type="text" id="newSession" name="sessionid"><br>
        Select Version:
        <select id="version" name="version">
          <option value="techYes">Techniques Enabled</option>
          <option value="techNo">Undo Enabled</option>
        </select>
        <input class = "modal-button" type="button" onclick="changeSession()" value="Submit">
      </form>
    </div>
  </div>

  <div id="myModal2" class="modal">
    <div class="modal-content">
          <%= link_to "BEGIN TUTORIAL", sketchtrainings_path, class: "menuButton"%>
    </div>
  </div>

	<div class="row">

		<% @molecules.each do |molecule| %>
			<% counter = counter + 1 %>

			<% if counter % 3 == 1 %>
				<%= link_to molecule, class: 'col-md-3 boxed firstBox', :action => 'go' do %>
					<p class="molecule_formula">

					</p>
					<p class="molecule_name"><%=molecule.name%></p>
				<% end %>
			<% else %>
				<%= link_to molecule, class: 'col-md-3 boxed', :action => 'go' do %>
					<p class="molecule_formula">

					</p>
					<p class="molecule_name"><%=molecule.name%></p>
				<% end %>
			<% end %>

			<% if counter % 3 == 0 %>
				</div>
				<div class="row">
			<% end %>


		<% end %>
	</div>
</div>

<script type="text/javascript">
  $(document).ready(function () {
    var s_id = "<%= @sessionID %>";
    var s_ver = "<%= @version %>";
    setSession(s_id, s_ver);
    // Get the modal
    var modal = document.getElementById('myModal');

    // Get the button that opens the modal
    var btn = document.getElementById("myBtn");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks on the button, open the modal
    btn.onclick = function() {
      modal.style.display = "block";
    }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
      modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
      if (event.target == modal) {
        modal.style.display = "none";
      }
    }

  });

</script>

app/views/molecules/show.html.erb
<body class="sketchbody">

 <div class="row" id="sketchpadapp">

    <div class="col-md-7">
      <div class="mainHeader headerblue">
            <h2><%= link_to "chemisketch", {controller: "molecules", action: "index"}, class: "colorBlue"%></h2>
      </div>
        <div class="row">
            <canvas id="sketchpad" height="600" width="600" style="border:1px solid #707070; border-radius: 10px; box-shadow: 2px 4px 5px rgba(0, 0, 0, 0.2); background-color: white;">
            </canvas>
        </div>


    </div>
    <div class="col-md-5" id="infoSection">
      <h2 class="moleculeInfoName"><%= @molecule.name %> -

      </h2>
        <div id="moleculeInfo" class="row">
          <div class="col-md-6" id="moleculeInfoAvail">
          </div>
          <div class="col-md-6" id="moleculeInfoNeed">
          </div>
        </div>
        <p id="interp"></p>
        <p id="displayArea"></p>
        <div class="row resultBox correctStatus" id="result1">

        </div>
        <div class="row resultBox" id="result2">

        </div>
        <div class="row resultBox" id="result3">

        </div>
        <div class="row resultBox" id="result4">

        </div>

        <div class="backButtonSection" id="doneButton">
          <% if (@molecule.next_molecule) %>
            <%= link_to "NEXT", @molecule.next_molecule, class: "backButton", id: "backToHome"%>
          <% else %>
            <%= link_to "NEXT", root_path, class: "backButton", id: "backToHome"%>
          <% end %>
        </div>
    </div>


 </div>
 <div class="row menu">
     <div class="col-md-2">
         <input class="button" type="submit" value="CLEAR" onclick="clearButton();">
     </div>

     <div class="col-md-2">
         <input class="button" type="submit" value="CHECK" onclick="checkAnswer();">
     </div>
     <div class="col-md-2" id="undoButton">
       <input class="button" type="submit" value="UNDO" onclick="undoSketch();">
    </div>

 </div>
 <script type="text/javascript">

 $(document).ready(function() {
    window.onload = init();

    var myCanvas = document.querySelector("#sketchpad");
    myCanvas.width = document.documentElement.clientWidth*(9/20);

    myCanvas.height = document.documentElement.clientHeight*(3/4);
    var d = new Date();



	  var numberAtoms = <%= @numAtoms %>;
    var centralAtom = "<%= @cenAtom %>";
    var otherAtoms = "<%= @othAtoms %>";
    var fullElec = "<%= @fullElectrons %>";
    var availElec = "<%= @availElectrons %>";
    var molecule = "<%= @molecule.formula %>";
    var charge = "<%= @charge %>";
    var formalCharges = "<%= @formalCharges %>";

    var technique = {
      id: sessionID,
      molecule: molecule,
      time: d.getTime(),
      type: "start",
    };
    $.ajax({
      method: "POST",
      url: "/techniques",
      dataType:"json",
      data: technique,
      success: function(result){
        console.log("start recorded");
      }

    });

    addAtoms(numberAtoms, centralAtom, otherAtoms, fullElec, availElec, molecule, charge, formalCharges);
    drawRegions();

});

</script>
</body>

app/views/posts/_form.html.erb
 <%= form_for @post do |f| %>
 	<%= f.label :title %><br>
 	<%= f.text_field :title %><br>
 	<br>
 	<%= f.label :body %><br>
 	<%= f.text_area :body %><br>
 	<br>
 	<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
 <h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<body onload="init()">
 <div id="sketchpadapp">
    
    <div class="rightside">
        <canvas id="sketchpad" height="500" width="800">
        </canvas>
        <div class="row menu">
        	<div class="column left">
        		<input class="button" type="submit" value="CLEAR" onclick="clearCanvas(canvas,ctx);">
        	</div>
        	
        </div>
    </div>
 </div>
</body>

app/views/posts/new.html.erb
 <h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<div><%= @post.body %></div>

<%= link_to "Edit Post", edit_post_path(@post) %>

<%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure?"} %>

app/views/sketchtrainings/_form.html.erb
 <%= form_for @sketchtraining do |f| %>
 	<%= f.label :interpretation %><br>
 	<%= f.text_field :interpretation %><br>
 	<br>
 	
 	<%= f.submit %>
<% end %>

app/views/sketchtrainings/index.html.erb
<body class="sketchbody">
  <div class="mainHeader headerblue row">
          <div class="col-md-8">
            <h2>tutorial</h2>
          </div>

  </div>
 <div class="row" id="sketchpadapp">

    <div class="col-md-7">

        <div class="row">
            <canvas id="sketchpad" height="550" width="550" style="border:1px solid #707070; border-radius: 10px; box-shadow: 2px 4px 5px rgba(0, 0, 0, 0.2); background-color: white;">
            </canvas>
        </div>


    </div>
    <div class="col-md-5">
        <h2 class="moleculeInfoName">

        </h2>
        <div id="moleculeInfo" class="row">
          <div class="col-md-6" id="moleculeInfoAvail">
          </div>
          <div class="col-md-6" id="moleculeInfoNeed">
          </div>
        </div>
        <div class="row resultBox" id="trainingInstruction1">

        </div>
        <div class="row resultBox" id="trainingInstruction2">

        </div>
        <div class="row resultBox" id="trainingInstruction3">

        </div>
        <div class = "row" id="nextButton">
          <input class="button" type="submit" value="NEXT" onclick="nextTutorial();">
        </div>
        <div class = "row" id="startButton">
          <%= link_to "START", @molecule, class: "backButton", id: "backToHome"%>
        </div>
    </div>

 </div>


<script type="text/javascript">
  $(document).ready(function () {

    window.onload = training_init();


    <% @sketchtrainings.each do |sketchtraining| %>
    	console.log("<%= sketchtraining.interpretation %>")
    <% end %>

  });

</script>
</body>

app/views/sketchtrainings/show.html.erb
<script type="text/javascript">
  $(document).ready(function () {
    var allTrainings = [];
    <% @sketchtrainings.each do |training| %>
      var trainingObject = {
        cosineStartAngle: <%= training.cosineStartAngle %>,
        sineStartAngle: <%= training.sineStartAngle %>,
        BBDiagLen: <%= training.bbDiagLen %>,
        BBDiagAngle: <%= training.bbDiagAngle %>,
        startEndDist: <%= training.startEndDist %>,
        startEndCosineAngle: <%= training.startEndCosineAngle %>,
        startEndSineAngle: <%= training.startEndSineAngle %>,
        strokeLength: <%= training.strokeLength %>,
        angleTrav9: <%= training.angleTrav9 %>,
        angleTrav10: <%= training.angleTrav10 %>,
        angleTrav11: <%= training.angleTrav11 %>,
        maxSpeed: <%= training.maxSpeed %>,
        pathDuration: <%= training.pathDuration %>,
        interpretation: "<%= training.interpretation %>",
      };
      allTrainings.push(trainingObject)
    <% end %>

    tr_downloadCSV(allTrainings);

  });

</script>

app/views/techniques/index.html.erb
<div class="techniqueTable">
  <div class="row">
    <div class="col-md-8">
      <h2>Technique Records</h2>
    </div>
    <div class="col-md-4">
      <input class="button" type="submit" value="SAVE TECHNIQUES" onclick="saveTechniques();">
    </div>
  </div>
  <table>
    <tr>
      <th>Session ID</th>
      <th>Molecule</th>
      <th>Type</th>
      <th>Time</th>
    </tr>
    <% @techniques.each do |technique| %>
    <tr>
      <td><%=technique.session%></td>
      <td><%=technique.molecule%></td>
      <td><%=technique.techType%></td>
      <td><%=technique.time%></td>
    </tr>
    <% end %>

  </table>
</div>

<script type="text/javascript">
  $(document).ready(function () {
    var techSaved = [];
    <% @techniques.each do |technique| %>
      var techObject = {
        session: "<%= technique.session %>",
        molecule: "<%= technique.molecule %>",
        type: "<%= technique.techType %>",
        time: <%= technique.time %>,
      };
      techSaved.push(techObject)
    <% end %>
    techInit(techSaved);

  });

</script>